# NUMPY 

## Numpy Array

In [2]:
import numpy as np

In [5]:
#dimensions of data 
a1d = np.array([1,2,3]) # 1D-array / Vector
a2d = np.array([[1,0,3],[4,5,6]]) # 2D-array / Matrix
a3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[5,6,4]]]) # 3D-array / Matriz  

In [10]:
print( "Array 1 : " , a1d )
print( "\nArray 2 : \n" , a2d )
print( "\nArray 3 : \n" , a3d )

Array 1 :  [1 2 3]

Array 2 : 
 [[1 0 3]
 [4 5 6]]

Array 3 : 
 [[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [5 6 4]]]


In [13]:
#shapes of array 
print( "Shape of Array 1 : " , a1d.shape )
print( "Shape of Array 2 : " , a2d.shape )
print( "Shape of Array 3 : " , a3d.shape )

Shape of Array 1 :  (3,)
Shape of Array 2 :  (2, 3)
Shape of Array 3 :  (2, 2, 3)


In [14]:
#dimension of array
print( "Dimension of Array 1 : " , a1d.ndim )
print( "Dimension of Array 2 : " , a2d.ndim )
print( "Dimenension of Array 3 : " , a3d.ndim )

Dimension of Array 1 :  1
Dimension of Array 2 :  2
Dimenension of Array 3 :  3


In [15]:
a3d.dtype

dtype('int32')

In [16]:
a3d.size #tells no. of entries/elements in an array 

12

In [19]:
#we can create dataframe out of  numpy bcz pandas is written in numpy
import pandas as pd
df = pd.DataFrame(a2d)
df

0  1  2
0  1  0  3
1  4  5  6

## Creating numpy Arrays (using functions)

In [20]:
# 3 types of functions 
# zeros, ones, random

In [6]:
zeros = np.zeros((2,2))
ones = np.ones((2,3))
print("Zeros\n",zeros,"\n")
print("Ones\n",ones )

Zeros
 [[0. 0.]
 [0. 0.]] 

Ones
 [[1. 1. 1.]
 [1. 1. 1.]]


In [27]:
range_arr = np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [29]:
np.random.randint(0,10, size=(2,3))

array([[9, 7, 2],
       [2, 5, 8]])

In [32]:
np.random.rand(3,3) #auto range 0-1

array([[0.36870152, 0.82977402, 0.77224261],
       [0.64172843, 0.36773337, 0.92290724],
       [0.54007519, 0.91984641, 0.26836452]])

In [34]:
# to save the state of randomness
np.random.seed(seed = 0)
np.random.rand(3,5)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

## Accessing Elements of Array 

In [35]:
a2d

array([[1, 0, 3],
       [4, 5, 6]])

In [57]:
a2d[0]

array([1, 0, 3])

In [58]:
a2d[0][2]

3

In [37]:
a3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [5, 6, 4]]])

In [56]:
a3d[1]

array([[7, 8, 9],
       [5, 6, 4]])

In [55]:
a3d[:1,:1,:2]

array([[[1, 2]]])

In [39]:
a3d[:2]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [5, 6, 4]]])

In [42]:
a3d[0:2,:1]

array([[[1, 2, 3]],

       [[7, 8, 9]]])

In [45]:
a3d[0:2,:1,:2]

array([[[1, 2]],

       [[7, 8]]])

In [59]:
arandom = np.random.randint(10, size = (2,2)) #2D
arandom

array([[9, 4],
       [3, 0]])

In [60]:
arandom = np.random.randint(10, size = (2,2,2)) #3D
arandom

array([[[3, 5],
        [0, 2]],

       [[3, 8],
        [1, 3]]])

In [61]:
arandom = np.random.randint(10, size = (3,3,3)) #3D
arandom

array([[[3, 3, 7],
        [0, 1, 9],
        [9, 0, 4]],

       [[7, 3, 2],
        [7, 2, 0],
        [0, 4, 5]],

       [[5, 6, 8],
        [4, 1, 4],
        [9, 8, 1]]])

In [3]:
arandom = np.random.randint(10, size = (2,3,4,5)) #3D
arandom

array([[[[4, 0, 8, 9, 1],
         [9, 7, 5, 1, 7],
         [9, 3, 8, 9, 1],
         [2, 1, 9, 7, 4]],

        [[4, 2, 7, 4, 2],
         [0, 4, 3, 0, 4],
         [7, 7, 3, 3, 3],
         [6, 9, 3, 0, 7]],

        [[0, 0, 5, 9, 8],
         [9, 1, 9, 1, 0],
         [7, 0, 5, 8, 6],
         [6, 6, 9, 0, 3]]],


       [[[5, 1, 7, 9, 2],
         [5, 8, 7, 7, 7],
         [4, 9, 6, 3, 4],
         [0, 1, 9, 3, 8]],

        [[0, 7, 1, 7, 4],
         [0, 7, 9, 6, 6],
         [4, 7, 3, 9, 0],
         [3, 7, 2, 1, 3]],

        [[7, 6, 3, 3, 9],
         [5, 7, 6, 1, 6],
         [4, 4, 4, 6, 8],
         [0, 9, 7, 9, 9]]]])

In [64]:
arandom[0:2,:1,:1,:1]

array([[[[1]]],


       [[[4]]]])

In [4]:
arandom[0:1,:2,:2,:2]

array([[[[4, 0],
         [9, 7]],

        [[4, 2],
         [0, 4]]]])

## Array Manipulation

In [8]:
a1d

array([1, 2, 3])

In [9]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Broadcasting

In [10]:
a1d+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [11]:
a1d*ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [12]:
a2d

array([[1, 0, 3],
       [4, 5, 6]])

In [15]:
a3d = np.array([[[1, 2, 3,4],[4, 5, 6,9]] , [[7, 8, 9,5],[5, 6, 4,1]]] )
a3d

array([[[1, 2, 3, 4],
        [4, 5, 6, 9]],

       [[7, 8, 9, 5],
        [5, 6, 4, 1]]])

In [23]:
sliced_a3d = a3d[:2,:2,:3]
sliced_a3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [5, 6, 4]]])

In [24]:
a2d*sliced_a3d

array([[[ 1,  0,  9],
        [16, 25, 36]],

       [[ 7,  0, 27],
        [20, 30, 24]]])

In [25]:
a1d/ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [28]:
a2d/a1d

array([[1. , 0. , 1. ],
       [4. , 2.5, 2. ]])

In [29]:
a2d//a1d

array([[1, 0, 1],
       [4, 2, 2]])

In [30]:
a1d**2

array([1, 4, 9])

In [31]:
np.square(a2d)

array([[ 1,  0,  9],
       [16, 25, 36]])

In [34]:
np.add(a1d,ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [35]:
a2d%2

array([[1, 0, 1],
       [0, 1, 0]], dtype=int32)

## Agregations

In [36]:
a1d

array([1, 2, 3])

In [37]:
sum(a1d) #python method :: slower

6

In [38]:
np.sum(a1d) #numpy method :: faster

6

In [40]:
large_arr=np.random.random(10000)

In [42]:
large_arr[:20]

array([0.28847325, 0.27855304, 0.12108584, 0.60782652, 0.56763639,
       0.33905713, 0.16349045, 0.1216411 , 0.33030909, 0.15361116,
       0.03063218, 0.9425765 , 0.49590887, 0.29781843, 0.99513396,
       0.23747275, 0.56006197, 0.39925826, 0.16327208, 0.11440207])

In [44]:
%timeit sum(large_arr) #python sum

2.11 ms ± 254 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [45]:
%timeit np.sum(large_arr) #numpy sum

16.7 µs ± 165 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [46]:
np.max(a1d)

3

In [47]:
np.min(a1d)

1

#### mean, variance, std

In [49]:
np.mean(a1d)

2.0

In [50]:
np.var(a1d)

0.6666666666666666

In [51]:
np.sqrt(np.var(a1d))

0.816496580927726

In [54]:
np.std(a1d)

0.816496580927726

## Matrix Multiplication Vs Dot Product

### Matrix Multiplication

In [73]:
matrix_1 = np.random.randint(10,size=(4,3))
matrix_1

array([[0, 5, 8],
       [5, 6, 6],
       [6, 7, 1],
       [2, 5, 4]])

In [74]:
matrix_2 = np.random.randint(10,size=(4,3))
matrix_2

array([[3, 7, 9],
       [4, 9, 7],
       [4, 8, 3],
       [3, 4, 4]])

In [75]:
matrix_1*matrix_2 #element wise multiplication 

array([[ 0, 35, 72],
       [20, 54, 42],
       [24, 56,  3],
       [ 6, 20, 16]])

### Dot Product

In [80]:
matrix_1.dot(matrix_2.T)

array([[107, 101,  64,  52],
       [111, 116,  86,  63],
       [ 76,  94,  83,  50],
       [ 77,  81,  60,  42]])

##### reshape 

In [81]:
#intruduces artificial columns in matrix

In [82]:
a2d

array([[1, 0, 3],
       [4, 5, 6]])

In [84]:
a2d.reshape(2,3,1)

array([[[1],
        [0],
        [3]],

       [[4],
        [5],
        [6]]])

## Generate daily , weekly total sales of a store

In [88]:
np.random.seed(seed=10)
price=np.array([12,11,9])

In [106]:
import pandas as pd 
item_price_df = pd.DataFrame(price.reshape(1,3),index=['item_price'],columns=['item_1','item_2','item_3'])
item_price_df

item_1  item_2  item_3
item_price      12      11       9

In [98]:
item_amount_sold=np.random.randint(20, size=(5,3))
item_amount

array([[ 4, 15, 11],
       [11,  1,  8],
       [ 4, 14, 17],
       [19, 13,  5],
       [13, 19, 13]])

In [100]:
item_amount_sold_df=pd.DataFrame(item_amount,index=['Mon','Tue','Wed','Thur','Fri'],columns=['item_1','item_2','item_3'])
item_amount_sold_df

item_1  item_2  item_3
Mon        4      15      11
Tue       11       1       8
Wed        4      14      17
Thur      19      13       5
Fri       13      19      13

In [127]:
total_sale=item_amount_sold.dot(price.reshape(3,1))

array([[191],
       [458],
       [354],
       [455],
       [445]])

In [116]:
total_sale_df=pd.DataFrame(total_sale,index=['Mon','Tue','Wed','Thur','Fri'],columns=['total_sale_price'])
total_sale_df

total_sale_price
Mon                191
Tue                458
Wed                354
Thur               455
Fri                445

In [140]:
item_amount_sold_df['total_sale_price']=total_sale
item_amount_sold_df

item_1  item_2  item_3  total_sale_pricce  total_sale_price
Mon        4      15      11                191               191
Tue       11       1       8                458               458
Wed        4      14      17                354               354
Thur      19      13       5                455               455
Fri       13      19      13                445               445

In [142]:
total_week_sale=np.sum(total_sale)

## Comparision Operators

In [143]:
a1d

array([1, 2, 3])

In [144]:
a2d

array([[1, 0, 3],
       [4, 5, 6]])

In [146]:
a1d>a2d #element wise comparision

array([[False,  True, False],
       [False, False, False]])

In [147]:
a1d<a2d

array([[False, False, False],
       [ True,  True,  True]])

In [148]:
a1d==a2d

array([[ True, False,  True],
       [False, False, False]])

In [149]:
a1d!=a2d

array([[False,  True, False],
       [ True,  True,  True]])

## Sorting Array

In [152]:
rand_mat=np.random.randint(10,size=(3,5))
rand_mat

array([[6, 6, 5, 6, 0],
       [0, 6, 9, 1, 8],
       [9, 1, 2, 8, 9]])

In [153]:
np.sort(rand_mat) #by default rows are sorted

array([[0, 5, 6, 6, 6],
       [0, 1, 6, 8, 9],
       [1, 2, 8, 9, 9]])

In [154]:
np.sort(rand_mat,axis=0) #to sort columns

array([[0, 1, 2, 1, 0],
       [6, 6, 5, 6, 8],
       [9, 6, 9, 8, 9]])

In [155]:
np.argsort(rand_mat) #it will tell index of elements to be sorted

array([[4, 2, 0, 1, 3],
       [0, 3, 1, 4, 2],
       [1, 2, 3, 0, 4]], dtype=int64)

In [156]:
np.argmin(rand_mat) #it shows index of minimum value in whole matrix 

4

In [160]:
np.argmin(rand_mat,axis=0)

array([1, 2, 2, 1, 0], dtype=int64)

In [161]:
np.argmin(rand_mat,axis=1)

array([4, 0, 1], dtype=int64)

In [162]:
np.argmax(rand_mat) #it shows index of maximum value in whole matrix 

7

In [163]:
np.argmax(rand_mat,axis=0)

array([2, 0, 1, 2, 2], dtype=int64)

In [165]:
np.argmax(rand_mat,axis=1)

array([0, 2, 0], dtype=int64)